default_stages: [commit]
fail_fast: true

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: pretty-format-json
    args: [--autofix]
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: name-tests-test
    args: [--pytest-test-first]
    types: [python]
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    args: [--line-length=120]
    types: [python]

- repo: https://github.com/timothycrosley/isort
  rev: 5.11.5
  hooks:
  - id: isort
    args: [--profile=black]
    types: [python]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py311-plus]
    types: [python]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--max-line-length=120]
    types: [python]
